import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Paper,
  Button,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Grid,
  MenuItem,
  Select,
  FormControl,
  InputLabel,
  Tabs,
  Tab,
  Card,
  CardContent,
  Alert,
  CircularProgress,
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import EditIcon from '@mui/icons-material/Edit';
import VisibilityIcon from '@mui/icons-material/Visibility';
import DownloadIcon from '@mui/icons-material/Download';
import Layout from '../../components/Layout';
import api from '../../services/api';
import { useNotification } from '../../contexts/NotificationContext';

function HRManagement() {
  const { showSuccess, showError } = useNotification();
  const [loading, setLoading] = useState(false);
  const [employees, setEmployees] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [designations, setDesignations] = useState([]);
  const [payrolls, setPayrolls] = useState([]);
  const [tabValue, setTabValue] = useState(0);
  
  // Employee Dialog
  const [employeeDialogOpen, setEmployeeDialogOpen] = useState(false);
  
  // Department Dialog
  const [departmentDialogOpen, setDepartmentDialogOpen] = useState(false);
  const [departmentForm, setDepartmentForm] = useState({
    code: '',
    name: '',
    description: '',
  });
  
  // Designation Dialog
  const [designationDialogOpen, setDesignationDialogOpen] = useState(false);
  const [designationForm, setDesignationForm] = useState({
    code: '',
    name: '',
    description: '',
    level: 0,
  });
  const [employeeForm, setEmployeeForm] = useState({
    employee_code: '',
    first_name: '',
    last_name: '',
    phone: '',
    email: '',
    department_id: '',
    designation_id: '',
    joining_date: new Date().toISOString().split('T')[0],
    bank_name: '',
    bank_account_number: '',
    bank_ifsc_code: '',
  });

  useEffect(() => {
    fetchEmployees();
    fetchDepartments();
    fetchDesignations();
    fetchPayrolls();
  }, []);

  const fetchEmployees = async () => {
    try {
      setLoading(true);
      const response = await api.get('/api/v1/hr/employees');
      setEmployees(response.data);
    } catch (err) {
      showError('Failed to fetch employees');
    } finally {
      setLoading(false);
    }
  };

  const fetchDepartments = async () => {
    try {
      const response = await api.get('/api/v1/hr/departments');
      setDepartments(response.data);
    } catch (err) {
      console.error('Failed to fetch departments:', err);
    }
  };

  const fetchDesignations = async () => {
    try {
      const response = await api.get('/api/v1/hr/designations');
      setDesignations(response.data);
    } catch (err) {
      console.error('Failed to fetch designations:', err);
    }
  };

  const fetchPayrolls = async () => {
    try {
      const response = await api.get('/api/v1/hr/payrolls?limit=50');
      setPayrolls(response.data);
    } catch (err) {
      console.error('Failed to fetch payrolls:', err);
    }
  };

  const handleCreateEmployee = async () => {
    try {
      setLoading(true);
      // Remove employee_code if empty (will be auto-generated by backend)
      const formData = { ...employeeForm };
      if (!formData.employee_code || formData.employee_code.trim() === '') {
        delete formData.employee_code;
      }
      await api.post('/api/v1/hr/employees', formData);
      showSuccess('Employee created successfully');
      setEmployeeDialogOpen(false);
      setEmployeeForm({
        employee_code: '',
        first_name: '',
        last_name: '',
        phone: '',
        email: '',
        department_id: '',
        designation_id: '',
        joining_date: new Date().toISOString().split('T')[0],
        bank_name: '',
        bank_account_number: '',
        bank_ifsc_code: '',
      });
      fetchEmployees();
    } catch (err) {
      showError(err.response?.data?.detail || 'Failed to create employee');
    } finally {
      setLoading(false);
    }
  };

  const handleCreateDepartment = async () => {
    try {
      setLoading(true);
      await api.post('/api/v1/hr/departments', departmentForm);
      showSuccess('Department created successfully');
      setDepartmentDialogOpen(false);
      setDepartmentForm({
        code: '',
        name: '',
        description: '',
      });
      fetchDepartments();
    } catch (err) {
      showError(err.response?.data?.detail || 'Failed to create department');
    } finally {
      setLoading(false);
    }
  };

  const handleCreateDesignation = async () => {
    try {
      setLoading(true);
      await api.post('/api/v1/hr/designations', designationForm);
      showSuccess('Designation created successfully');
      setDesignationDialogOpen(false);
      setDesignationForm({
        code: '',
        name: '',
        description: '',
        level: 0,
      });
      fetchDesignations();
    } catch (err) {
      showError(err.response?.data?.detail || 'Failed to create designation');
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadSalarySlip = async (payrollId) => {
    try {
      const response = await api.get(`/api/v1/hr/payrolls/${payrollId}/salary-slip`, {
        responseType: 'blob',
      });
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `salary_slip_${payrollId}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      
      showSuccess('Salary slip downloaded');
    } catch (err) {
      showError('Failed to download salary slip');
    }
  };

  const getStatusColor = (status) => {
    const colors = {
      active: 'success',
      inactive: 'default',
      resigned: 'warning',
      terminated: 'error',
      on_leave: 'info',
    };
    return colors[status] || 'default';
  };

  const getPayrollStatusColor = (status) => {
    const colors = {
      draft: 'default',
      processed: 'info',
      approved: 'warning',
      paid: 'success',
      cancelled: 'error',
    };
    return colors[status] || 'default';
  };

  return (
    <Layout>
      <Box sx={{ p: 3 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
          <Typography variant="h4" component="h1">
            HR & Payroll Management
          </Typography>
          <Box sx={{ display: 'flex', gap: 2 }}>
            {tabValue === 0 && (
              <>
                <Button
                  variant="outlined"
                  startIcon={<AddIcon />}
                  onClick={() => setDepartmentDialogOpen(true)}
                >
                  Add Department
                </Button>
                <Button
                  variant="outlined"
                  startIcon={<AddIcon />}
                  onClick={() => setDesignationDialogOpen(true)}
                >
                  Add Designation
                </Button>
                <Button
                  variant="contained"
                  startIcon={<AddIcon />}
                  onClick={() => setEmployeeDialogOpen(true)}
                >
                  Add Employee
                </Button>
              </>
            )}
          </Box>
        </Box>

        <Paper sx={{ mb: 3 }}>
          <Tabs value={tabValue} onChange={(e, newValue) => setTabValue(newValue)}>
            <Tab label="Employees" />
            <Tab label="Payrolls" />
          </Tabs>
        </Paper>

        {tabValue === 0 && (
          <TableContainer component={Paper}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Employee Code</TableCell>
                  <TableCell>Name</TableCell>
                  <TableCell>Department</TableCell>
                  <TableCell>Designation</TableCell>
                  <TableCell>Phone</TableCell>
                  <TableCell>Joining Date</TableCell>
                  <TableCell>Status</TableCell>
                  <TableCell>Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={8} align="center">
                      <CircularProgress />
                    </TableCell>
                  </TableRow>
                ) : employees.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} align="center">
                      <Alert severity="info">No employees found. Add your first employee to get started.</Alert>
                    </TableCell>
                  </TableRow>
                ) : (
                  employees.map((employee) => (
                    <TableRow key={employee.id}>
                      <TableCell>{employee.employee_code}</TableCell>
                      <TableCell>{employee.full_name}</TableCell>
                      <TableCell>{employee.department_name || 'N/A'}</TableCell>
                      <TableCell>{employee.designation_name || 'N/A'}</TableCell>
                      <TableCell>{employee.phone}</TableCell>
                      <TableCell>{new Date(employee.joining_date).toLocaleDateString()}</TableCell>
                      <TableCell>
                        <Chip
                          label={employee.status}
                          color={getStatusColor(employee.status)}
                          size="small"
                        />
                      </TableCell>
                      <TableCell>
                        <IconButton size="small" color="primary">
                          <EditIcon />
                        </IconButton>
                        <IconButton size="small" color="info">
                          <VisibilityIcon />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </TableContainer>
        )}

        {tabValue === 1 && (
          <TableContainer component={Paper}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Employee</TableCell>
                  <TableCell>Period</TableCell>
                  <TableCell>Gross Salary</TableCell>
                  <TableCell>Deductions</TableCell>
                  <TableCell>Net Salary</TableCell>
                  <TableCell>Status</TableCell>
                  <TableCell>Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={7} align="center">
                      <CircularProgress />
                    </TableCell>
                  </TableRow>
                ) : payrolls.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} align="center">
                      <Alert severity="info">No payrolls found. Process payroll for employees to see records.</Alert>
                    </TableCell>
                  </TableRow>
                ) : (
                  payrolls.map((payroll) => (
                    <TableRow key={payroll.id}>
                      <TableCell>{payroll.employee_name}</TableCell>
                      <TableCell>{payroll.payroll_month}/{payroll.payroll_year}</TableCell>
                      <TableCell>₹{payroll.gross_salary.toLocaleString()}</TableCell>
                      <TableCell>₹{payroll.total_deductions.toLocaleString()}</TableCell>
                      <TableCell>₹{payroll.net_salary.toLocaleString()}</TableCell>
                      <TableCell>
                        <Chip
                          label={payroll.status}
                          color={getPayrollStatusColor(payroll.status)}
                          size="small"
                        />
                      </TableCell>
                      <TableCell>
                        <IconButton
                          size="small"
                          color="primary"
                          onClick={() => handleDownloadSalarySlip(payroll.id)}
                          disabled={payroll.status === 'draft'}
                        >
                          <DownloadIcon />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </TableContainer>
        )}

        {/* Employee Dialog */}
        <Dialog open={employeeDialogOpen} onClose={() => setEmployeeDialogOpen(false)} maxWidth="md" fullWidth>
          <DialogTitle>Add New Employee</DialogTitle>
          <DialogContent>
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="First Name"
                  value={employeeForm.first_name}
                  onChange={(e) => setEmployeeForm({ ...employeeForm, first_name: e.target.value })}
                  required
                />
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Last Name"
                  value={employeeForm.last_name}
                  onChange={(e) => setEmployeeForm({ ...employeeForm, last_name: e.target.value })}
                />
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Phone"
                  value={employeeForm.phone}
                  onChange={(e) => setEmployeeForm({ ...employeeForm, phone: e.target.value })}
                  required
                />
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Email"
                  type="email"
                  value={employeeForm.email}
                  onChange={(e) => setEmployeeForm({ ...employeeForm, email: e.target.value })}
                />
              </Grid>
              <Grid item xs={12} sm={6}>
                <FormControl fullWidth>
                  <InputLabel>Department</InputLabel>
                  <Select
                    value={employeeForm.department_id}
                    onChange={(e) => setEmployeeForm({ ...employeeForm, department_id: e.target.value })}
                    label="Department"
                    required
                  >
                    {departments.length === 0 ? (
                      <MenuItem disabled>No departments found. Click "Add Department" to create one.</MenuItem>
                    ) : (
                      departments.map((dept) => (
                        <MenuItem key={dept.id} value={dept.id}>
                          {dept.name}
                        </MenuItem>
                      ))
                    )}
                  </Select>
                </FormControl>
                {departments.length === 0 && (
                  <Typography variant="caption" color="error" sx={{ mt: 0.5, ml: 1.5 }}>
                    No departments available. Please add a department first.
                  </Typography>
                )}
              </Grid>
              <Grid item xs={12} sm={6}>
                <FormControl fullWidth>
                  <InputLabel>Designation</InputLabel>
                  <Select
                    value={employeeForm.designation_id}
                    onChange={(e) => setEmployeeForm({ ...employeeForm, designation_id: e.target.value })}
                    label="Designation"
                    required
                  >
                    {designations.length === 0 ? (
                      <MenuItem disabled>No designations found. Click "Add Designation" to create one.</MenuItem>
                    ) : (
                      designations.map((desig) => (
                        <MenuItem key={desig.id} value={desig.id}>
                          {desig.name}
                        </MenuItem>
                      ))
                    )}
                  </Select>
                </FormControl>
                {designations.length === 0 && (
                  <Typography variant="caption" color="error" sx={{ mt: 0.5, ml: 1.5 }}>
                    No designations available. Please add a designation first.
                  </Typography>
                )}
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Joining Date"
                  type="date"
                  value={employeeForm.joining_date}
                  onChange={(e) => setEmployeeForm({ ...employeeForm, joining_date: e.target.value })}
                  InputLabelProps={{ shrink: true }}
                  required
                />
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Bank Name"
                  value={employeeForm.bank_name}
                  onChange={(e) => setEmployeeForm({ ...employeeForm, bank_name: e.target.value })}
                />
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Account Number"
                  value={employeeForm.bank_account_number}
                  onChange={(e) => setEmployeeForm({ ...employeeForm, bank_account_number: e.target.value })}
                />
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="IFSC Code"
                  value={employeeForm.bank_ifsc_code}
                  onChange={(e) => setEmployeeForm({ ...employeeForm, bank_ifsc_code: e.target.value })}
                />
              </Grid>
            </Grid>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setEmployeeDialogOpen(false)}>Cancel</Button>
            <Button
              variant="contained"
              onClick={handleCreateEmployee}
              disabled={loading || !employeeForm.first_name || !employeeForm.phone || !employeeForm.department_id || !employeeForm.designation_id}
            >
              {loading ? <CircularProgress size={20} /> : 'Create'}
            </Button>
          </DialogActions>
        </Dialog>

        {/* Department Dialog */}
        <Dialog open={departmentDialogOpen} onClose={() => setDepartmentDialogOpen(false)} maxWidth="sm" fullWidth>
          <DialogTitle>Add New Department</DialogTitle>
          <DialogContent>
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Department Code"
                  value={departmentForm.code}
                  onChange={(e) => setDepartmentForm({ ...departmentForm, code: e.target.value.toUpperCase() })}
                  required
                  helperText="Short code (e.g., HR, ADMIN, POOJA)"
                  inputProps={{ maxLength: 20 }}
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Department Name"
                  value={departmentForm.name}
                  onChange={(e) => setDepartmentForm({ ...departmentForm, name: e.target.value })}
                  required
                  helperText="Full department name"
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Description"
                  value={departmentForm.description}
                  onChange={(e) => setDepartmentForm({ ...departmentForm, description: e.target.value })}
                  multiline
                  rows={3}
                />
              </Grid>
            </Grid>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setDepartmentDialogOpen(false)}>Cancel</Button>
            <Button
              variant="contained"
              onClick={handleCreateDepartment}
              disabled={loading || !departmentForm.code || !departmentForm.name}
            >
              {loading ? <CircularProgress size={20} /> : 'Create'}
            </Button>
          </DialogActions>
        </Dialog>

        {/* Designation Dialog */}
        <Dialog open={designationDialogOpen} onClose={() => setDesignationDialogOpen(false)} maxWidth="sm" fullWidth>
          <DialogTitle>Add New Designation</DialogTitle>
          <DialogContent>
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Designation Code"
                  value={designationForm.code}
                  onChange={(e) => setDesignationForm({ ...designationForm, code: e.target.value.toUpperCase() })}
                  required
                  helperText="Short code (e.g., MGR, CLERK, PRIEST)"
                  inputProps={{ maxLength: 20 }}
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Designation Name"
                  value={designationForm.name}
                  onChange={(e) => setDesignationForm({ ...designationForm, name: e.target.value })}
                  required
                  helperText="Full designation name"
                />
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  fullWidth
                  label="Level"
                  type="number"
                  value={designationForm.level}
                  onChange={(e) => setDesignationForm({ ...designationForm, level: parseInt(e.target.value) || 0 })}
                  helperText="Hierarchy level (0 = lowest)"
                  inputProps={{ min: 0 }}
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Description"
                  value={designationForm.description}
                  onChange={(e) => setDesignationForm({ ...designationForm, description: e.target.value })}
                  multiline
                  rows={3}
                />
              </Grid>
            </Grid>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setDesignationDialogOpen(false)}>Cancel</Button>
            <Button
              variant="contained"
              onClick={handleCreateDesignation}
              disabled={loading || !designationForm.code || !designationForm.name}
            >
              {loading ? <CircularProgress size={20} /> : 'Create'}
            </Button>
          </DialogActions>
        </Dialog>
      </Box>
    </Layout>
  );
}

export default HRManagement;

