"""
Hindu Constants for Temple Management
Contains common Hindu religious data like Gothras, Nakshatras, and Rashis
"""

# 50 Common Hindu Gothras (Lineages)
GOTHRAS = [
    "Agastya",
    "Angirasa",
    "Atri",
    "Bharadwaja",
    "Bhargava",
    "Bhrigu",
    "Dhananjaya",
    "Garga",
    "Gautama",
    "Harita",
    "Jamadagni",
    "Kashyapa",
    "Katyayana",
    "Kaundinya",
    "Kausika",
    "Kaushika",
    "Kratu",
    "Kutsa",
    "Lomasha",
    "Mandavya",
    "Marichi",
    "Moudgalya",
    "Naidhruva",
    "Parashara",
    "Pulaha",
    "Pulastya",
    "Sandilya",
    "Shandilya",
    "Sankrithi",
    "Srivatsa",
    "Upamanyu",
    "Valmiki",
    "Vashishta",
    "Vatsa",
    "Vishwamitra",
    "Viswamitra",
    "Vrigu",
    "Yaska",
    "Kanva",
    "Mudgala",
    "Raibhya",
    "Uddālaka",
    "Agni",
    "Aliman",
    "Kapi",
    "Krivi",
    "Kapi",
    "Saunaka",
    "Vadula",
    "Vasistha",
]

# 27 Nakshatras (Lunar Mansions)
NAKSHATRAS = [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Moola",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishta",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
]

# 12 Rashis (Zodiac Signs)
RASHIS = [
    "Mesha (Aries)",
    "Vrishabha (Taurus)",
    "Mithuna (Gemini)",
    "Karka (Cancer)",
    "Simha (Leo)",
    "Kanya (Virgo)",
    "Tula (Libra)",
    "Vrishchika (Scorpio)",
    "Dhanu (Sagittarius)",
    "Makara (Capricorn)",
    "Kumbha (Aquarius)",
    "Meena (Pisces)",
]
